### ISSUE TITLE
7.2 not found?

### ISSUE THREAD

**Issue by Inari-Whitebear** [kariae/symfony-php#2]
I seem to be unable to acquire the 7.2 image.

```docker` pull kariae/symfony-php:7.2
Error response from daemon: manifest for kariae/symfony-php:7.2 not found```

:latest works but running that with "php -v" says PHP 7.1.20. :7 works too, but same thing. Docker's page doesn't seem to list the 7.2 tag either.

**Comment by kariae** [comment]
My bad, forgot to push the 7.2 version after the merge request, done, it's working now :)

**Comment by Inari-Whitebear** [comment]
Nice, thanks!
